# Generated by Django 5.2.7 on 2025-12-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='state',
            field=models.CharField(default='current', max_length=64),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_paid',
            field=models.FloatField(default=0),
        ),
    ]
