# Generated by Django 5.2.7 on 2025-11-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platecategory',
            name='label',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
