# Generated by Django 5.2.7 on 2025-12-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
