# Generated by Django 5.2.7 on 2025-12-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_bill_state_alter_bill_tip_alter_bill_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
