# Generated by Django 5.2.7 on 2025-11-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_platecategory_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plate',
            options={'ordering': ['category__label', 'name']},
        ),
        migrations.AlterField(
            model_name='tablearea',
            name='label',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
