# Generated by Django 5.2.7 on 2025-11-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_plate_options_alter_tablearea_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
