# Generated by Django 5.2.7 on 2025-12-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_emailvalidationcode'),
        ('backend', '0003_alter_bill_date_time'),
    ]

    operations = [
    ]
