# Generated by Django 5.2.7 on 2025-12-06 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_merge_20251206_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateCookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked', models.BooleanField(default=False)),
                ('cooked_at', models.DateTimeField(blank=True, null=True)),
                ('bill_plate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_status', to='backend.billplate')),
            ],
            options={
                'verbose_name': 'Plate Cooking Status',
                'verbose_name_plural': 'Plate Cooking Statuses',
            },
        ),
    ]
