# Generated by Django 5.2.7 on 2025-12-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_reservation_notes_alter_table_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Bill',
        ),
        migrations.RenameModel(
            old_name='AccountPlate',
            new_name='BillPlate',
        ),
    ]
