# Generated by Django 5.2.7 on 2025-12-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_add_plate_cooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billplate',
            name='cooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billplate',
            name='cooked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PlateCookingStatus',
        ),
    ]
